#pragma once

#include <hephaestus/Platform.h>
#include <hephaestus/VulkanPlatformConfig.h>


#define HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(fun) PFN_##fun fun = 0

namespace hephaestus
{

// Dispatcher to be used with Vulkan.hpp objects so that Vulkan functions can be loaded dynamically
// See DispatchLoaderDynamic in vulkan.hpp for available functions (per platform)
struct VulkanDispatcher
{

#ifdef HEPHAESTUS_PLATFORM_WIN32
    typedef HMODULE ModuleType; // win32
#elif defined(HEPHAESTUS_PLATFORM_LINUX)
    typedef void* ModuleType;
#elif defined(HEPHAESTUS_PLATFORM_ANDROID)
    typedef void* ModuleType;
#endif

    static VulkanDispatcher& GetInstance();

    static void InitFromLibrary(ModuleType vulkanLibrary);
    static void LoadGlobalFunctions();
    static void LoadInstanceFunctions(const vk::Instance& instance);
    static void LoadDeviceFunctions(const vk::Device& device);


    // always exported functions
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetInstanceProcAddr);


    // global functions 
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateInstance);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkEnumerateInstanceVersion);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkEnumerateInstanceExtensionProperties);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkEnumerateInstanceLayerProperties);


    // instance functions
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkEnumeratePhysicalDevices);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetPhysicalDeviceProperties);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetPhysicalDeviceFeatures);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetPhysicalDeviceQueueFamilyProperties);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateDevice);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetDeviceProcAddr);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyInstance);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetPhysicalDeviceMemoryProperties);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkEnumerateDeviceExtensionProperties);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetPhysicalDeviceSurfaceSupportKHR);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetPhysicalDeviceSurfaceCapabilitiesKHR);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetPhysicalDeviceSurfaceFormatsKHR);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetPhysicalDeviceSurfacePresentModesKHR);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroySurfaceKHR);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateDebugUtilsMessengerEXT);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyDebugUtilsMessengerEXT);
#ifdef HEPHAESTUS_PLATFORM_WIN32
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateWin32SurfaceKHR); // win32
#elif defined(HEPHAESTUS_PLATFORM_LINUX)
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateXlibSurfaceKHR); // xlib
#elif defined(HEPHAESTUS_PLATFORM_ANDROID)
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateAndroidSurfaceKHR); // android
#endif

    // device functions
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetDeviceQueue);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDeviceWaitIdle);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyDevice);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateSemaphore);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateCommandPool);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkAllocateCommandBuffers);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkBeginCommandBuffer);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdPipelineBarrier);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdClearColorImage);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkEndCommandBuffer);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkQueueSubmit);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkFreeCommandBuffers);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyCommandPool);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroySemaphore);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateSwapchainKHR);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetSwapchainImagesKHR);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkAcquireNextImageKHR);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkQueuePresentKHR);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroySwapchainKHR);

    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateImage);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateImageView);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateRenderPass);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateFramebuffer);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateShaderModule);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreatePipelineLayout);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateGraphicsPipelines);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdBeginRenderPass);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdBindPipeline);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdDraw);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdEndRenderPass);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyShaderModule);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyPipelineLayout);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyPipeline);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyRenderPass);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyFramebuffer);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyImageView);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyImage);

    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateFence);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateBuffer);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetBufferMemoryRequirements);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkAllocateMemory);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkBindBufferMemory);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkMapMemory);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkFlushMappedMemoryRanges);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkUnmapMemory);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdSetViewport);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdSetScissor);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdBindVertexBuffers);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkWaitForFences);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkResetFences);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkFreeMemory);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyBuffer);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyFence);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdCopyBuffer);

    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetImageMemoryRequirements);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkBindImageMemory);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateSampler);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdCopyBufferToImage);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateDescriptorSetLayout);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCreateDescriptorPool);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkAllocateDescriptorSets);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkUpdateDescriptorSets);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdBindDescriptorSets);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyDescriptorPool);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroyDescriptorSetLayout);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkDestroySampler);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkFreeDescriptorSets);

    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdBindIndexBuffer);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdDrawIndexed);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdPushConstants);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkResetCommandPool);

    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdSetLineWidth);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkCmdCopyImage);
    HEPHAESTUS_VULKAN_EXPORTEDFUNCTION_DECLARATION(vkGetImageSubresourceLayout);
};

}